/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIChatMessage { 'content' : string, 'role' : string }
export interface Article {
  'id' : string,
  'status' : string,
  'title' : string,
  'content' : string,
  'views' : bigint,
  'authorId' : Principal,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'authorName' : string,
  'likes' : bigint,
  'dislikes' : bigint,
}
export interface CibilCheckInput {
  'scoreRange' : string,
  'factors' : Array<CibilFactor>,
  'sessionId' : string,
  'estimatedScore' : bigint,
}
export interface CibilFactor { 'key' : string, 'value' : string }
export type CourseId = string;
export type EnrollResult = { 'ok' : null } |
  { 'err' : string };
export interface Experience {
  'id' : string,
  'difficulty' : string,
  'createdAt' : Timestamp,
  'role' : string,
  'authorName' : string,
  'company' : string,
  'experienceText' : string,
}
export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
  'status_code' : number,
}
export interface LoanApplication {
  'id' : LoanApplicationId,
  'loanAmount' : bigint,
  'city' : string,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'employmentType' : string,
  'propertyValue' : [] | [bigint],
  'loanType' : string,
  'message' : string,
  'existingEMI' : bigint,
  'panNumber' : string,
  'phone' : string,
  'monthlyIncome' : bigint,
}
export type LoanApplicationId = string;
export interface LoanApplicationInput {
  'loanAmount' : bigint,
  'city' : string,
  'name' : string,
  'email' : string,
  'employmentType' : string,
  'propertyValue' : [] | [bigint],
  'loanType' : string,
  'message' : string,
  'existingEMI' : bigint,
  'panNumber' : string,
  'phone' : string,
  'monthlyIncome' : bigint,
}
export interface MeetingRequest {
  'id' : MeetingRequestId,
  'topic' : string,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'preferredTime' : string,
  'phone' : string,
}
export type MeetingRequestId = string;
export interface MeetingRequestInput {
  'topic' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'preferredTime' : string,
  'phone' : string,
}
export interface Message {
  'role' : string,
  'text' : string,
  'timestamp' : bigint,
}
export interface MockTestResult {
  'id' : string,
  'completedAt' : Timestamp,
  'userId' : Principal,
  'answers' : Array<string>,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timeTaken' : bigint,
  'testId' : string,
}
export interface MonthlyReport {
  'id' : MonthlyReportId,
  'yearMonth' : string,
  'generatedAt' : Timestamp,
  'meetingRequests' : Array<MeetingRequest>,
  'excelLink' : [] | [string],
  'loanApplications' : Array<LoanApplication>,
}
export type MonthlyReportId = string;
export interface MonthlyReportInput { 'yearMonth' : string }
export interface Note {
  'id' : string,
  'title' : string,
  'content' : string,
  'userId' : Principal,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'topicId' : string,
}
export type Personality = { 'calm' : null } |
  { 'playful' : null } |
  { 'encouraging' : null } |
  { 'witty' : null };
export interface ProgressReport {
  'xp' : bigint,
  'username' : string,
  'badges' : Array<string>,
  'quizzesPassedCount' : bigint,
  'streakDays' : bigint,
  'level' : bigint,
  'completedTopicsCount' : bigint,
  'enrolledCourses' : Array<string>,
}
export interface Question {
  'topic' : string,
  'correctIndex' : bigint,
  'xpReward' : bigint,
  'answers' : Array<string>,
  'difficulty' : bigint,
  'text' : string,
}
export interface Review {
  'id' : bigint,
  'name' : string,
  'comment' : string,
  'timestamp' : Timestamp,
  'rating' : bigint,
}
export type Timestamp = bigint;
export interface UserProfile {
  'xp' : bigint,
  'personality' : Personality,
  'username' : string,
  'messagesSent' : bigint,
  'badges' : Array<string>,
  'streakDays' : bigint,
  'level' : bigint,
  'burnoutScore' : bigint,
  'lastActive' : bigint,
  'completedTopics' : Array<string>,
  'companionName' : string,
}
export type VerifyResult = { 'ok' : null } |
  { 'err' : string };
export interface _SERVICE {
  'addMessage' : ActorMethod<[string, string], undefined>,
  'addSampleQuestions' : ActorMethod<[], undefined>,
  'awardBadge' : ActorMethod<[string], undefined>,
  'awardGCoins' : ActorMethod<[bigint], bigint>,
  'completeTopic' : ActorMethod<[string], undefined>,
  'deleteNote' : ActorMethod<[string], boolean>,
  'dislikeArticle' : ActorMethod<[string], boolean>,
  'enrollCourse' : ActorMethod<[string], EnrollResult>,
  'followUser' : ActorMethod<[string], boolean>,
  'generateMonthlyReport' : ActorMethod<[MonthlyReportInput], MonthlyReport>,
  'getAllStats' : ActorMethod<[], UserProfile>,
  'getArticles' : ActorMethod<[string], Array<Article>>,
  'getEnrolledCourses' : ActorMethod<[], Array<CourseId>>,
  'getExperiences' : ActorMethod<[], Array<Experience>>,
  'getGCoins' : ActorMethod<[], bigint>,
  'getHistory' : ActorMethod<[], Array<Message>>,
  'getMockTestResults' : ActorMethod<[], Array<MockTestResult>>,
  'getMonthlyReports' : ActorMethod<[], Array<MonthlyReport>>,
  'getMyFollowers' : ActorMethod<[], Array<string>>,
  'getMyFollowing' : ActorMethod<[], Array<string>>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getOrCreateProfile' : ActorMethod<[string], UserProfile>,
  'getProgressReport' : ActorMethod<[], ProgressReport>,
  'getQuestionsByTopic' : ActorMethod<[string], Array<Question>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'incrementArticleView' : ActorMethod<[string], boolean>,
  'isFollowingUser' : ActorMethod<[string], boolean>,
  'likeArticle' : ActorMethod<[string], boolean>,
  'proxyAIChat' : ActorMethod<[Array<AIChatMessage>, string], string>,
  'saveCibilCheck' : ActorMethod<[CibilCheckInput], string>,
  'saveMockTestResult' : ActorMethod<
    [string, bigint, bigint, bigint, Array<string>],
    MockTestResult
  >,
  'saveNote' : ActorMethod<[string, string, string], Note>,
  'sendVerificationEmail' : ActorMethod<[string], undefined>,
  'submitArticle' : ActorMethod<
    [string, string, Array<string>, string],
    Article
  >,
  'submitExperience' : ActorMethod<
    [string, string, string, string, string],
    Experience
  >,
  'submitLoanApplication' : ActorMethod<[LoanApplicationInput], string>,
  'submitMeetingRequest' : ActorMethod<[MeetingRequestInput], string>,
  'submitReview' : ActorMethod<
    [string, bigint, string],
    { 'ok' : Review } |
      { 'err' : string }
  >,
  'unenrollCourse' : ActorMethod<[string], EnrollResult>,
  'unfollowUser' : ActorMethod<[string], boolean>,
  'updateCompanion' : ActorMethod<[string, Personality], undefined>,
  'updateNote' : ActorMethod<[string, string, string], [] | [Note]>,
  'verifyEmail' : ActorMethod<[string, string], VerifyResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];