/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EnrollResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const MonthlyReportInput = IDL.Record({ 'yearMonth' : IDL.Text });
export const MonthlyReportId = IDL.Text;
export const Timestamp = IDL.Int;
export const MeetingRequestId = IDL.Text;
export const MeetingRequest = IDL.Record({
  'id' : MeetingRequestId,
  'topic' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'preferredTime' : IDL.Text,
  'phone' : IDL.Text,
});
export const LoanApplicationId = IDL.Text;
export const LoanApplication = IDL.Record({
  'id' : LoanApplicationId,
  'loanAmount' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'employmentType' : IDL.Text,
  'propertyValue' : IDL.Opt(IDL.Nat),
  'loanType' : IDL.Text,
  'message' : IDL.Text,
  'existingEMI' : IDL.Nat,
  'panNumber' : IDL.Text,
  'phone' : IDL.Text,
  'monthlyIncome' : IDL.Nat,
});
export const MonthlyReport = IDL.Record({
  'id' : MonthlyReportId,
  'yearMonth' : IDL.Text,
  'generatedAt' : Timestamp,
  'meetingRequests' : IDL.Vec(MeetingRequest),
  'excelLink' : IDL.Opt(IDL.Text),
  'loanApplications' : IDL.Vec(LoanApplication),
});
export const Personality = IDL.Variant({
  'calm' : IDL.Null,
  'playful' : IDL.Null,
  'encouraging' : IDL.Null,
  'witty' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'personality' : Personality,
  'username' : IDL.Text,
  'messagesSent' : IDL.Nat,
  'badges' : IDL.Vec(IDL.Text),
  'streakDays' : IDL.Nat,
  'level' : IDL.Nat,
  'burnoutScore' : IDL.Nat,
  'lastActive' : IDL.Int,
  'completedTopics' : IDL.Vec(IDL.Text),
  'companionName' : IDL.Text,
});
export const Article = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'views' : IDL.Nat,
  'authorId' : IDL.Principal,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'likes' : IDL.Nat,
  'dislikes' : IDL.Nat,
});
export const CourseId = IDL.Text;
export const Experience = IDL.Record({
  'id' : IDL.Text,
  'difficulty' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : IDL.Text,
  'authorName' : IDL.Text,
  'company' : IDL.Text,
  'experienceText' : IDL.Text,
});
export const Message = IDL.Record({
  'role' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const MockTestResult = IDL.Record({
  'id' : IDL.Text,
  'completedAt' : Timestamp,
  'userId' : IDL.Principal,
  'answers' : IDL.Vec(IDL.Text),
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timeTaken' : IDL.Nat,
  'testId' : IDL.Text,
});
export const Note = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'topicId' : IDL.Text,
});
export const ProgressReport = IDL.Record({
  'xp' : IDL.Nat,
  'username' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'quizzesPassedCount' : IDL.Nat,
  'streakDays' : IDL.Nat,
  'level' : IDL.Nat,
  'completedTopicsCount' : IDL.Nat,
  'enrolledCourses' : IDL.Vec(IDL.Text),
});
export const Question = IDL.Record({
  'topic' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'xpReward' : IDL.Nat,
  'answers' : IDL.Vec(IDL.Text),
  'difficulty' : IDL.Nat,
  'text' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'comment' : IDL.Text,
  'timestamp' : Timestamp,
  'rating' : IDL.Nat,
});
export const HttpRequest = IDL.Record({
  'url' : IDL.Text,
  'method' : IDL.Text,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const HttpResponse = IDL.Record({
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'status_code' : IDL.Nat16,
});
export const AIChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const CibilFactor = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
export const CibilCheckInput = IDL.Record({
  'scoreRange' : IDL.Text,
  'factors' : IDL.Vec(CibilFactor),
  'sessionId' : IDL.Text,
  'estimatedScore' : IDL.Nat,
});
export const LoanApplicationInput = IDL.Record({
  'loanAmount' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'employmentType' : IDL.Text,
  'propertyValue' : IDL.Opt(IDL.Nat),
  'loanType' : IDL.Text,
  'message' : IDL.Text,
  'existingEMI' : IDL.Nat,
  'panNumber' : IDL.Text,
  'phone' : IDL.Text,
  'monthlyIncome' : IDL.Nat,
});
export const MeetingRequestInput = IDL.Record({
  'topic' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'preferredTime' : IDL.Text,
  'phone' : IDL.Text,
});
export const VerifyResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addSampleQuestions' : IDL.Func([], [], []),
  'awardBadge' : IDL.Func([IDL.Text], [], []),
  'awardGCoins' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'completeTopic' : IDL.Func([IDL.Text], [], []),
  'deleteNote' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'dislikeArticle' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'enrollCourse' : IDL.Func([IDL.Text], [EnrollResult], []),
  'followUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'generateMonthlyReport' : IDL.Func([MonthlyReportInput], [MonthlyReport], []),
  'getAllStats' : IDL.Func([], [UserProfile], ['query']),
  'getArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'getEnrolledCourses' : IDL.Func([], [IDL.Vec(CourseId)], ['query']),
  'getExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'getGCoins' : IDL.Func([], [IDL.Nat], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getMockTestResults' : IDL.Func([], [IDL.Vec(MockTestResult)], ['query']),
  'getMonthlyReports' : IDL.Func([], [IDL.Vec(MonthlyReport)], ['query']),
  'getMyFollowers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMyFollowing' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getOrCreateProfile' : IDL.Func([IDL.Text], [UserProfile], []),
  'getProgressReport' : IDL.Func([], [ProgressReport], ['query']),
  'getQuestionsByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
  'incrementArticleView' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'isFollowingUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'likeArticle' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'proxyAIChat' : IDL.Func([IDL.Vec(AIChatMessage), IDL.Text], [IDL.Text], []),
  'saveCibilCheck' : IDL.Func([CibilCheckInput], [IDL.Text], []),
  'saveMockTestResult' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text)],
      [MockTestResult],
      [],
    ),
  'saveNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Note], []),
  'sendVerificationEmail' : IDL.Func([IDL.Text], [], []),
  'submitArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [Article],
      [],
    ),
  'submitExperience' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Experience],
      [],
    ),
  'submitLoanApplication' : IDL.Func([LoanApplicationInput], [IDL.Text], []),
  'submitMeetingRequest' : IDL.Func([MeetingRequestInput], [IDL.Text], []),
  'submitReview' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : Review, 'err' : IDL.Text })],
      [],
    ),
  'unenrollCourse' : IDL.Func([IDL.Text], [EnrollResult], []),
  'unfollowUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateCompanion' : IDL.Func([IDL.Text, Personality], [], []),
  'updateNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Opt(Note)], []),
  'verifyEmail' : IDL.Func([IDL.Text, IDL.Text], [VerifyResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EnrollResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const MonthlyReportInput = IDL.Record({ 'yearMonth' : IDL.Text });
  const MonthlyReportId = IDL.Text;
  const Timestamp = IDL.Int;
  const MeetingRequestId = IDL.Text;
  const MeetingRequest = IDL.Record({
    'id' : MeetingRequestId,
    'topic' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'preferredTime' : IDL.Text,
    'phone' : IDL.Text,
  });
  const LoanApplicationId = IDL.Text;
  const LoanApplication = IDL.Record({
    'id' : LoanApplicationId,
    'loanAmount' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'employmentType' : IDL.Text,
    'propertyValue' : IDL.Opt(IDL.Nat),
    'loanType' : IDL.Text,
    'message' : IDL.Text,
    'existingEMI' : IDL.Nat,
    'panNumber' : IDL.Text,
    'phone' : IDL.Text,
    'monthlyIncome' : IDL.Nat,
  });
  const MonthlyReport = IDL.Record({
    'id' : MonthlyReportId,
    'yearMonth' : IDL.Text,
    'generatedAt' : Timestamp,
    'meetingRequests' : IDL.Vec(MeetingRequest),
    'excelLink' : IDL.Opt(IDL.Text),
    'loanApplications' : IDL.Vec(LoanApplication),
  });
  const Personality = IDL.Variant({
    'calm' : IDL.Null,
    'playful' : IDL.Null,
    'encouraging' : IDL.Null,
    'witty' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'personality' : Personality,
    'username' : IDL.Text,
    'messagesSent' : IDL.Nat,
    'badges' : IDL.Vec(IDL.Text),
    'streakDays' : IDL.Nat,
    'level' : IDL.Nat,
    'burnoutScore' : IDL.Nat,
    'lastActive' : IDL.Int,
    'completedTopics' : IDL.Vec(IDL.Text),
    'companionName' : IDL.Text,
  });
  const Article = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'views' : IDL.Nat,
    'authorId' : IDL.Principal,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'likes' : IDL.Nat,
    'dislikes' : IDL.Nat,
  });
  const CourseId = IDL.Text;
  const Experience = IDL.Record({
    'id' : IDL.Text,
    'difficulty' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : IDL.Text,
    'authorName' : IDL.Text,
    'company' : IDL.Text,
    'experienceText' : IDL.Text,
  });
  const Message = IDL.Record({
    'role' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const MockTestResult = IDL.Record({
    'id' : IDL.Text,
    'completedAt' : Timestamp,
    'userId' : IDL.Principal,
    'answers' : IDL.Vec(IDL.Text),
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timeTaken' : IDL.Nat,
    'testId' : IDL.Text,
  });
  const Note = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'topicId' : IDL.Text,
  });
  const ProgressReport = IDL.Record({
    'xp' : IDL.Nat,
    'username' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'quizzesPassedCount' : IDL.Nat,
    'streakDays' : IDL.Nat,
    'level' : IDL.Nat,
    'completedTopicsCount' : IDL.Nat,
    'enrolledCourses' : IDL.Vec(IDL.Text),
  });
  const Question = IDL.Record({
    'topic' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'xpReward' : IDL.Nat,
    'answers' : IDL.Vec(IDL.Text),
    'difficulty' : IDL.Nat,
    'text' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'comment' : IDL.Text,
    'timestamp' : Timestamp,
    'rating' : IDL.Nat,
  });
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'status_code' : IDL.Nat16,
  });
  const AIChatMessage = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const CibilFactor = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const CibilCheckInput = IDL.Record({
    'scoreRange' : IDL.Text,
    'factors' : IDL.Vec(CibilFactor),
    'sessionId' : IDL.Text,
    'estimatedScore' : IDL.Nat,
  });
  const LoanApplicationInput = IDL.Record({
    'loanAmount' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'employmentType' : IDL.Text,
    'propertyValue' : IDL.Opt(IDL.Nat),
    'loanType' : IDL.Text,
    'message' : IDL.Text,
    'existingEMI' : IDL.Nat,
    'panNumber' : IDL.Text,
    'phone' : IDL.Text,
    'monthlyIncome' : IDL.Nat,
  });
  const MeetingRequestInput = IDL.Record({
    'topic' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'preferredTime' : IDL.Text,
    'phone' : IDL.Text,
  });
  const VerifyResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addSampleQuestions' : IDL.Func([], [], []),
    'awardBadge' : IDL.Func([IDL.Text], [], []),
    'awardGCoins' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'completeTopic' : IDL.Func([IDL.Text], [], []),
    'deleteNote' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'dislikeArticle' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'enrollCourse' : IDL.Func([IDL.Text], [EnrollResult], []),
    'followUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'generateMonthlyReport' : IDL.Func(
        [MonthlyReportInput],
        [MonthlyReport],
        [],
      ),
    'getAllStats' : IDL.Func([], [UserProfile], ['query']),
    'getArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
    'getEnrolledCourses' : IDL.Func([], [IDL.Vec(CourseId)], ['query']),
    'getExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'getGCoins' : IDL.Func([], [IDL.Nat], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getMockTestResults' : IDL.Func([], [IDL.Vec(MockTestResult)], ['query']),
    'getMonthlyReports' : IDL.Func([], [IDL.Vec(MonthlyReport)], ['query']),
    'getMyFollowers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMyFollowing' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getOrCreateProfile' : IDL.Func([IDL.Text], [UserProfile], []),
    'getProgressReport' : IDL.Func([], [ProgressReport], ['query']),
    'getQuestionsByTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'incrementArticleView' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'isFollowingUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'likeArticle' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'proxyAIChat' : IDL.Func(
        [IDL.Vec(AIChatMessage), IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCibilCheck' : IDL.Func([CibilCheckInput], [IDL.Text], []),
    'saveMockTestResult' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text)],
        [MockTestResult],
        [],
      ),
    'saveNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Note], []),
    'sendVerificationEmail' : IDL.Func([IDL.Text], [], []),
    'submitArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [Article],
        [],
      ),
    'submitExperience' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Experience],
        [],
      ),
    'submitLoanApplication' : IDL.Func([LoanApplicationInput], [IDL.Text], []),
    'submitMeetingRequest' : IDL.Func([MeetingRequestInput], [IDL.Text], []),
    'submitReview' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : Review, 'err' : IDL.Text })],
        [],
      ),
    'unenrollCourse' : IDL.Func([IDL.Text], [EnrollResult], []),
    'unfollowUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateCompanion' : IDL.Func([IDL.Text, Personality], [], []),
    'updateNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(Note)],
        [],
      ),
    'verifyEmail' : IDL.Func([IDL.Text, IDL.Text], [VerifyResult], []),
  });
};

export const init = ({ IDL }) => { return []; };